image: docker:stable

stages: 
    - test
    - build 
    - deploy

services:
    - docker:dind

variables:
    REPOSITORYNAME: "troyanderson.d/playlistservice"

  
test:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    stage: test
    script:
        - dotnet test


push_Image_to_GitlabRegsitry:
    only: 
        - master
    stage: build
    before_script:
        - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} 
    script:
        - docker build -t ${CI_REGISTRY}/${${REPOSITORYNAME}}:latest -f PlaylistService.Web/dockerfiles/Dockerfile PlaylistService.Web
        - docker push ${CI_REGISTRY}/${${REPOSITORYNAME}}:latest
    after_script:
        - docker logout ${CI_REGISTRY)}
    tags:
        - docker

#Todo replace external image with own or heroku cli image 
deploy_to_heroku:
    only:
        - master
    stage: deploy
    before_script:
        - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
        - docker pull ${CI_REGISTRY}/${${REPOSITORYNAME}}:latest
    script:
        - docker login --username=troyanderson.d@gmail.com --password=$HEROKU_API_KEY registry.heroku.com
        - docker tag  ${CI_REGISTRY}/${${REPOSITORYNAME}}:latest registry.heroku.com/playlistservice/web:latest
        - docker push registry.heroku.com/playlistservice/web:latest
        - "docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY wingrunr21/alpine-heroku-cli container:release web --app=playlistService"
    after_script:
        - docker logout registry.heroku.com
    

    